config/routes.rb
ALLOW_DOTS ||= /[a-zA-Z0-9_.:-]+/

Rails.application.routes.draw do

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'
  
  # Switch over to this when home page has been created
  root to: 'pages#home'
  # root :to => "catalogue#index"

  resources :catalog, controller: 'catalog', path: '/catalogue', :constraints => { :id => ALLOW_DOTS, :format => false }

  # Add LB healthcheck page
  get 'healthcheck/rails-status' => 'pages#rails_status'

  %w[home about contact cookies help].each do |page|
    get page, controller: 'pages', action: page
  end
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalogue, only: [:index], as: 'catalog', path: '/catalogue', controller: 'catalog', :constraints => { :id => ALLOW_DOTS, :format => false } do
    concerns :searchable
    concerns :range_searchable
  end
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalogue', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/advanced_controller.rb
# This class should NOT be generated into local app. If you generated
# into local app in a previous version, remove that, config is done
# in CatalogController now.
#
# Note that this NEEDS to sub-class CatalogController, so it gets any
# custom searching behavior you've added, and uses when fetching facets
# etc. It does that right now because BlacklightAdvancedSearch::AdvancedController
# is hard-coded to subclass CatalogController. 
#
# TODO: 
# This seperate controller may not need to exist at all -- it just exists
# to provide the advanced search form (and fetching of facets to display
# on that form). Instead, mix-in a new "advanced" action to CatalogController?
# (Make a backwards compat route though). 
#
# Alternately, if this does exist as a seperate controller, it should 
# _directly_ < CatalogController, and BlacklightAdvancedSearch::AdvancedController
# should be a mix-in that does not assume parent controller. Then, if you have
# multi-controllers, you just need to create new `AdvancedControllerForX < XController`
# which still mixes in BlacklightAdvancedSearch::AdvancedController. There
# are probably some other edges that need to be smoothed for that approach, but
# that'd be the direction. 
class AdvancedController < BlacklightAdvancedSearch::AdvancedController

  copy_blacklight_config_from(CatalogController)

end

app/views/advanced/_advanced_search_fields.html.erb
<%- search_fields_for_advanced_search.each do |key, field_def| -%>
  <div class="form-group advanced-search-field">
      <%= label_tag key, "#{field_def.label }", :class => "col-sm-3 control-label" %>
      <div class="col-sm-9">
        <%= text_field_tag key, label_tag_default_for(key), :class => 'form-control' %>
      </div>
  </div>
<%- end -%>

app/views/advanced/_advanced_search_form.html.erb
  <% unless (search_context_str = render_search_to_s( advanced_search_context)).blank? %>
    <div class="constraints well search_history">
      <h4><%= t 'blacklight_advanced_search.form.search_context' %></h4>
      <%= search_context_str %>
    </div>
  <% end %>

<%= form_tag catalog_index_path, :class => 'advanced form-horizontal', :method => :get do  %>

  <%= render_hash_as_hidden_fields(params_for_search(advanced_search_context, {})) %>

  <div class="input-criteria">

      <div class="query-criteria">
        <h3>Keywords</h3>
        <p class="query-criteria-heading">
          <%= t('blacklight_advanced_search.form.query_criteria_heading_html', :select_menu =>  select_menu_for_field_operator ) %> 
        </p>

        <div id="advanced_search">
          <%= render 'advanced/advanced_search_fields' %>
        </div>
      </div>
      
      <div class="limit-criteria">
        <p class="limit-criteria-heading"><%= t('blacklight_advanced_search.form.limit_criteria_heading_html')%></p>

        <%# Range searches for to/from %>
        <div class="form-group advanced-search-facet">
          <%= label_tag "publication_date", :class => "col-sm-3 control-label" do %>
              Date range:
          <% end %>
          <div class="col-sm-9">
              <%= render_range_input("dates_isim", :begin) %> - <%= render_range_input("dates_isim", :end) %>      
          </div>
        </div>
        <div id="advanced_search_facets" class="limit_input">
          <h3>Limit your search</h3>
          <% if blacklight_config.try(:advanced_search).try {|h| h[:form_facet_partial] } %>
            <%= render blacklight_config.advanced_search[:form_facet_partial] %>
          <% else %>
            <%= render 'advanced_search_facets' %>
          <% end %>
        </div>
      </div>
  <h3>Sort</h3>

  <div class="col-md-3">
    <%= label_tag(:sort, t('blacklight_advanced_search.form.sort_label'), :class => "control-label") %>
  </div>
  <div class="col-md-9">
    <%= select_tag(:sort, options_for_select(sort_fields, h(params[:sort])), :class => "form-control sort-select") %>
    <%= hidden_field_tag(:search_field, blacklight_config.advanced_search[:url_key]) %>
  </div>

  </div>

<hr>

  <div class="sort-submit-buttons col-md-12 clearfix">
    <%= render 'advanced_search_submit_btns' %>
  </div>

<% end %>

app/views/advanced/_advanced_search_help.html.erb
<div class='panel panel-default well'>
  <h3>Search tips</h3>
  <div class="panel-body">
    <ul class="advanced-help">
     <li>Select "match all" to require all fields.
     </li>

     <li>Select "match any" to find at least one field.
     </li>

     <li>Combine keywords and attributes to find specific items.
     </li>

     <li>Use quotation marks to search as a phrase.

     <li>Use "+" before a term to make it required. (Otherwise results matching only some of your terms may be included).</li>

     <li>Use "-" before a word or phrase to exclude.

     <li>Use "OR", "AND", and "NOT" to create complex boolean logic. You can use parentheses in your complex expressions. </li>
     <li>Truncation and wildcards are not supported - word-stemming is done automatically.</li>
   </ul>
  </div>
</div>

app/views/advanced/_advanced_search_submit_btns.html.erb
<div class="submit-buttons pull-right">
    <%= link_to t('blacklight_advanced_search.form.start_over'), blacklight_advanced_search_engine.advanced_search_path, :class =>"btn btn-default advanced-search-start-over" %>

    <%= submit_tag t('blacklight_advanced_search.form.search_btn'), :class=>'btn btn-primary advanced-search-submit', :id => "advanced-search-submit" %>
</div>

app/views/advanced/index.html.erb
<% @page_title = "Advanced search - #{application_name}" %>

<div class="col-sm-12">

    <h2>
        <%= t('blacklight_advanced_search.form.title') %>
        <%= link_to t('blacklight_advanced_search.form.start_over'), blacklight_advanced_search_engine.advanced_search_path, :class =>"btn btn-primary pull-right advanced-search-start-over" %>
    </h2>

    <div class="row">

        <div class="col-sm-8">
            <%= render 'advanced_search_form' %>
        </div>
        <div class="col-sm-4">
            <%= render "advanced_search_help" %>
        </div>

    </div>

</div>