config/routes.rb
ALLOW_DOTS ||= /[a-zA-Z0-9_.:-]+/

Rails.application.routes.draw do

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'
  
  # Switch over to this when home page has been created
  root to: 'pages#home'
  # root :to => "catalogue#index"

  resources :catalog, controller: 'catalog', path: '/catalogue', :constraints => { :id => ALLOW_DOTS, :format => false }

  # Add LB healthcheck page
  get 'healthcheck/rails-status' => 'pages#rails_status'

  %w[home about contact cookies help].each do |page|
    get page, controller: 'pages', action: page
  end
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalogue, only: [:index], as: 'catalog', path: '/catalogue', controller: 'catalog', :constraints => { :id => ALLOW_DOTS, :format => false } do
    concerns :searchable
    concerns :range_searchable
  end
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalogue', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/catalog_controller.rb
# frozen_string_literal: true
class CatalogController < ApplicationController
  include BlacklightGoogleAnalytics::ControllerExtraHead

  
   before_action :show_tab, only: :show

  include BlacklightRangeLimit::ControllerOverride
  include BlacklightAdvancedSearch::Controller
  include BlacklightGoogleAnalytics::ControllerExtraHead

  include Blacklight::Catalog
  
  configure_blacklight do |config|
    ## Default parameters to send to solr for all search-like requests. See also SolrHelper#solr_search_params
    config.default_solr_params = { 
      :qt => 'search',
      :rows => 10 
    }
    
    # solr path which will be added to solr base url before the other solr params.
    #config.solr_path = 'select' 
    
    # items to show per page, each number in the array represent another option to choose from.
    #config.per_page = [10,20,50,100]

    ## Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SolrHelper#solr_doc_params) or 
    ## parameters included in the Blacklight-jetty document requestHandler.
    #
    #config.default_document_solr_params = {
    #  :qt => 'document',
    #  ## These are hard-coded in the blacklight 'document' requestHandler
    #  # :fl => '*',
    #  # :rows => 1
    #  # :q => '{!raw f=id v=$id}' 
    #}

    # solr field configuration for search results/index views
    config.index.title_field = 'display_title_ss'
    #config.index.display_type_field = 'format'

    # solr field configuration for document/show views
    config.show.title_field = 'display_title_ss'
    #config.show.display_type_field = 'format'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.    
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or 
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.  
    #
    # :show may be set to false if you don't want the facet to be drawn in the 
    # facet bar
    config.add_facet_field 'format_ssi', label: 'Format', collapse: false, limit: 15, solr_params: { 'facet.mincount' => 1 }
    config.add_facet_field 'dates_isim', label: 'Date', :range => true, solr_params: { 'facet.mincount' => 1 }
    config.add_facet_field 'repository_ssi', label: 'Repository', limit: 5, solr_params: { 'facet.mincount' => 1 }
    config.add_facet_field 'subject_ssim', label: 'Subject', limit: 15, solr_params: { 'facet.mincount' => 1 }
    config.add_facet_field 'author_ssim', label: 'Author', limit: 15, solr_params: { 'facet.mincount' => 1 }
    config.add_facet_field 'collection_id_ssi', label: 'Collection', show: false, helper_method: :title_by_id, solr_params: { 'facet.mincount' => 1 }
    config.add_facet_field 'sub_collection_id_ssi', label: 'Subcollection', show: false, helper_method: :title_by_id, solr_params: { 'facet.mincount' => 1 }
    config.add_facet_field 'series_id_ssi', label: 'Series', show: false, helper_method: :title_by_id, solr_params: { 'facet.mincount' => 1 }
    config.add_facet_field 'sub_series_id_ssi', label: 'Subseries', show: false, helper_method: :title_by_id, solr_params: { 'facet.mincount' => 1 }
    config.add_facet_field 'online_ssi', label: 'Availability', collapse: true, solr_params: { 'facet.mincount' => 1 }

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display 
    config.add_index_field 'author_tesim', label: 'Author'
    config.add_index_field 'dates_ssim', label: 'Date'
    config.add_index_field 'extent_ssm', label: 'Extent'
    config.add_index_field 'reference_no_ssi', label: 'Reference No'
    config.add_index_field 'reference_no_search', label: 'Reference No'

    # solr fields to be displayed in the show (single result) view
    # The ordering of the field names is the order of the display
    # config.add_show_field 'reference_no_ssi', label: 'Reference No'
    # NB: These are set directly in the views for each type of record

    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #
    # Search fields will inherit the :qt solr request handler from
    # config[:default_solr_parameters], OR can specify a different one
    # with a :qt key/value. Below examples inherit, except for subject
    # that specifies the same :qt as default for our own internal
    # testing purposes.
    #
    # The :key is what will be used to identify this BL search field internally,
    # as well as in URLs -- so changing it after deployment may break bookmarked
    # urls.  A display label will be automatically calculated from the :key,
    # or can be specified manually to be different. 

    # This one uses all the defaults set by the solr request handler. Which
    # solr request handler? The one set in config[:default_solr_parameters][:qt],
    # since we aren't specifying it otherwise. 
    
    config.add_search_field 'all_fields', :label => 'All Fields'

#    config.add_search_field('title') do |field|
#      field.solr_parameters = {
#        :qf => '${title_qf}',
#        :pf => '${title_pf}'
#      }
#    end
#    config.add_search_field('author') do |field|
#      field.solr_parameters = {
#        :qf => '${author_qf}',
#        :pf => '${author_pf}'
#      }
#    end
#
#    config.add_search_field('subject') do |field|
#      field.solr_parameters = {
#        :qf => '${subject_qf}',
#        :pf => '${subject_pf}'
#      }
#    end
#   config.add_search_field('reference_no') do |field|
#      field.solr_parameters = {
#        :qf => '${reference_no_qf}',
#        :pf => '${reference_no_pf}'
#      }
#    end

    config.add_search_field('title') do |field|
      field.solr_local_parameters = {
        :qf => '$title_qf',
        :pf => '$title_pf'
      }
    end

    config.add_search_field('author') do |field|
      field.solr_local_parameters = {
        :qf => '$author_qf',
        :pf => '$author_pf'
      }
    end

    config.add_search_field('subject') do |field|
      field.solr_local_parameters = {
        :qf => '$subject_qf',
        :pf => '$subject_pf'
      }
    end

   config.add_search_field('reference_no') do |field|
      field.solr_local_parameters = {
        :qf => '$reference_no_qf',
        :pf => '$reference_no_pf'
      }
    end

    # "sort results by" select (pulldown)
    # label in pulldown is followed by the name of the SOLR field to sort by and
    # whether the sort is ascending or descending (it must be asc or desc
    # except in the relevancy case).
    config.add_sort_field 'score desc, title_ssi asc', :label => 'relevance'
    config.add_sort_field 'title_ssi asc, score desc', :label => 'title'
    config.add_sort_field 'date_ssi desc, title_ssi asc', :label => 'year'
    config.add_sort_field 'reference_no_ssort asc, score desc', :label => 'reference no.'

    # If there are more than this many search results, no spelling ("did you 
    # mean") suggestion is offered.
    config.spell_max = 5

      config.advanced_search = {
        :query_parser => 'edismax',
        :url_key => 'advanced',
        :form_solr_parameters => {
          'facet.field' => ['format_ssi', 'repository_ssi', 'subject_ssim', 'author_ssim', 'online_ssi'],
        }
      }

  end
  
  protected

  def show_tab
    @show_tab = params['tab']
  end

  # Override rails path for the views so that we can match up
  # app/views/catalog (from blacklight) with 'catalog' controller.
  def _prefixes
    @_prefixes ||= super + ['catalog']
  end
end

app/views/catalog/_availability_sidebar.html.erb
<div id="sidebar-nav" class="well square-corners">
  <ul class="nav nav-list">
    <li>
      <fieldset id="assets">
        <legend>
          <h3> Availability </h3>
        </legend>
        <div id="asset-list">
          <div class="clearfix">
            <% unless @document['type_ssi'] == 'library_record' %>
               <% if ead_item_access_closed?(@document) %>
                 <p><%= t('blacklight.show.item_closed_access') %></p>
                <% else %>
                  <% if @document['dao_ssi'] %>
                    <p><%= t('blacklight.show.item_open_online') %></p>
                    <% if @document['file_set_ids_ssim'] %>
                      <% images = false %>
                      <% urls = file_set_urls(@document.id) %>
                      <p>Downloads:</p>
                      <% if urls.length > 10 %>
                        <ul class="hhc_index"></ul>
                          <div class="hhc_pager">
                            <ul>
                            <% urls.each_with_index do | fs, index | %>
                              <% images = true if image?(fs['mime_type_ssi']) == true %>
                              <li><%= link_to fs['file_name_tesim'].first, file_set_url(fs['id']), "title" => fs['mime_type_ssi']  %> </li>
                              <% if (index+1) % 10 == 0 %>
                            </ul>
                            </div>
                            <div class="hhc_pager">
                            <ul>
                              <% end %>
                            <% end %>
                            </ul>
                          </div>
                      <% else %>
                          <ul>
                            <% urls.each_with_index do | fs, index | %>
                              <% images = true if image?(fs['mime_type_ssi']) == true %>
                              <li><%= link_to fs['file_name_tesim'].first, file_set_url(fs['id']), "title" => fs['mime_type_ssi']  %> </li>
                            <% end %>
                          </ul>
                      <% end %>
                      <% if images == true %>
                      <p>
                        <a href="#gotoviewer">
                          <button type="submit" class="btn btn-primary">View Images</button>
                        </a>
                      </p>
                      <% end %>
                    <% end %>
                  <% else %>
                    <p><%= t('blacklight.show.item_open_access') %></p>
                  <% end %>
                <% end %>
            <% end %>

            <label> Reference No: </label> <br />
            <%= @document['reference_no_ssi'] %>

            <% if @document["type_ssi"] == "library_record" && @document["repository_ssi"] == "Hull Local Studies Library" %>
              <p>
                <%= prism_search_link(@document["title_ssi"]) %>
              </p>
            <% end %>
          </div>
        </div>
      </fieldset>
    </li>
  </ul>
</div>

app/views/catalog/_document_list.html.erb
<% # container for all documents in index view -%>
<div id="documents">
  <%= render documents, :as => :document %>
</div>

app/views/catalog/_index_default.html.erb
<%# default partial to display solr document fields in catalog index view -%>
<dl class="document-metadata dl-horizontal dl-invert">
  <% index_fields(document).each do |solr_fname, field| %>
    <% if should_render_index_field? document, field %>
	    <dt class="blacklight-<%= solr_fname.parameterize %>"><%= render_index_field_label document, :field => solr_fname %></dt>
	    <dd class="blacklight-<%= solr_fname.parameterize %>"><%= render_index_field_value document, :field => solr_fname %></dd>
    <% end %>
  <% end %>
</dl>

app/views/catalog/_search_form.html.erb
<%= form_tag search_action_url, method: :get, class: 'search-query-form clearfix navbar-form', role: 'search' do %>
  <%= render_hash_as_hidden_fields(search_state.params_for_search.except(:q, :search_field, :qt, :page, :utf8)) %>
  <div class="input-group">
    <% if search_fields.length > 1 %>
      <span class="input-group-addon for-search-field">
        <label for="search_field" class="sr-only"><%= t('blacklight.search.form.search_field.label') %></label>
        <%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), title: t('blacklight.search.form.search_field.title'), id: "search_field", class: "search_field") %>
      </span>
    <% elsif search_fields.length == 1 %>
      <%= hidden_field_tag :search_field, search_fields.first.last %>
    <% end %>

    <label for="q" class="sr-only"><%= t('blacklight.search.form.search.label') %></label>
    <%= text_field_tag :q, params[:q], placeholder: t('blacklight.search.form.search.placeholder'), class: "search_q q form-control", id: "q", autofocus: should_autofocus_on_search_box?, data: { autocomplete_enabled: autocomplete_enabled?, autocomplete_path: blacklight.suggest_index_path }  %>

    <span class="input-group-btn">
      <button type="submit" class="btn btn-primary search-btn" id="search">
        <span class="submit-search-text"><%= t('blacklight.search.form.submit') %></span>
        <span class="glyphicon glyphicon-search"></span>
      </button>
    </span>
  </div>
<% end %>



<div class="navbar-form">
  <%= link_to 'More options', blacklight_advanced_search_engine.advanced_search_path(search_state.to_h), class: 'advanced_search btn btn-default'%>
</div>

app/views/catalog/_search_header.html.erb
<%= render 'sort_and_per_page' %>

<%= render 'did_you_mean' %>

<%= render 'constraints' %>

app/views/catalog/_show_collection.html.erb
<%# A show view for a single Collection -%>

<% unless document['dates_ssim'].blank? %>
  <h4>
    <dl class="dl-vertical  dl-invert">
      <dt> Dates: &nbsp; </dt>
      <dd> <%= Array(document['dates_ssim']).join(', ') %> </dd>
    </dl>
  </h4>
<% end %>

<div class="row">
  <% @show_tab ||= 'summary' %>

  <div id="tab-sidebar" class="col-sm-2">

    <%= display_resource_thumbnail (document) %>

    <% menu_item_classes = 'tab-menu-item col-md-12' %>

    <div class="tile-btn-fw-secondary">
      <%= link_to 'Summary', catalog_path(document.id, tab: 'summary'), class: "#{tab_class('summary', @show_tab)} #{menu_item_classes}" %>
    </div>

    <div class="tile-btn-fw-secondary">
      <%= link_to 'Description', catalog_path(document.id, tab: 'description'), class: "#{tab_class('description', @show_tab)} #{menu_item_classes}" %>
    </div>

    <div class="tile-btn-fw-secondary">
      <%= link_to 'Arrangement', catalog_path(document.id, tab: 'arrangement'), class: "#{tab_class('arrangement', @show_tab)} #{menu_item_classes}" %>
    </div>

    <div class="tile-btn-fw-secondary">
      <%= link_to 'Related Material', catalog_path(document.id, tab: 'related'), class: "#{tab_class('related', @show_tab)} #{menu_item_classes}" %>
    </div>

    <div class="tile-btn-fw-secondary">
      <%= link_to 'Search', catalog_path(document.id, tab: 'search'), class: "#{tab_class('search', @show_tab)} #{menu_item_classes}" %>
    </div>

  </div>

  <div id="tab-content" class="col-sm-10">
    <%= render "catalog/show_collection_#{@show_tab}", document: document %>
  </div>

</div>

app/views/catalog/_show_collection_arrangement.html.erb
<h3> Arrangement </h3>

<% if document['arrangement_ssm'].blank? %>
  No arrangement information available.
<% else %>
  <br />
  <div class='left-pad'>
    <%= Array(document['arrangement_ssm']).join('').html_safe %>
  </div>
<% end %>

app/views/catalog/_show_collection_description.html.erb
<h3> Description </h3>

<% show_fields = [['biog_hist_ssm', 'Admin History'],
                  ['description_tesim', 'Description']] %>

<dl class="dl-vertical dl-invert">
  <% show_fields.each do |(solr_doc_key, label)| %>
    <%= show_attribute(document, solr_doc_key, label) %>
  <% end %>
</dl>

app/views/catalog/_show_collection_summary.html.erb
<h3>Summary</h3>

<% show_fields = [['reference_no_ssi', 'Reference No'],
                  ['extent_ssm', 'Extent'],
                  ['language_ssim', 'Language'],
                  ['access_ssim', 'Access Conditions'],
                  ['copyright_ssm', 'Copyright'],
                  ['custodial_history_ssim', 'Custodial History']] %>

<dl class="dl-vertical  dl-invert">
  <% show_fields.each do |(solr_doc_key, label)| %>
    <%= show_attribute(document, solr_doc_key, label) %>
  <% end %>

  <dt> Permanent Link </dt>
  <dd> <%= catalog_url(document.id) %> </dd>

  <dt>Download</dt>
  <dd><%= collection_pdf_url(document.id, "Archive Catalogue (PDF format)") %></dd> 

  <%= show_attribute(document, 'repository_ssi', 'Repository') %>
</dl>

app/views/catalog/_show_item_access.html.erb
  <% is_collection = @document['type_ssi'] == 'collection' %>
  <% show_availability = @document['type_ssi'] == 'library_record'  || @document['type_ssi'] == 'item'  || @document['type_ssi'] == 'piece' %>
  <% show_item = @document['type_ssi'] == 'subseries'  || @document['type_ssi'] == 'subsubseries'|| @document['type_ssi'] == 'series'  || @document['type_ssi'] == 'subcollection' || @document['type_ssi'] == 'item' %>

  <% if show_availability && ! show_item %>
      <%= render 'catalog/availability',
                  document: @document %>
  <% end %>

  <% if show_item %>
      <%= render 'catalog/sub_items',
                  document: @document %>
  <% end %>

app/views/catalog/_show_item_images.html.erb
  <div class="viewer-wrapper">
    <iframe
      src="<%= request&.base_url %>/uv.html#?manifest=<%= manifest(@document['dao_ssi'])%>&config=<%= request&.base_url %>/uv_config.json" 
      allowfullscreen="true" 
      frameborder="0" 
    ></iframe>
  </div>

app/views/catalog/_show_piece.html.erb
<%# A show view for a single Piece -%>
<%= render 'show_item.html.erb', document: document %>

app/views/catalog/_sort_widget.html.erb
<% if show_sort_and_per_page? and !active_sort_fields.blank? %>
<div id="sort-dropdown" class="btn-group">
  <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown">
      <%= link_to(t('blacklight.search.sort.label', :field =>current_sort_field.label), "#") %> <span class="caret"></span>
  </button>

  <ul class="dropdown-menu" role="menu">
      <%- active_sort_fields.each do |sort_key, field_config| %>
        <li><%= link_to(field_config.label, url_for(params_for_search(:sort => sort_key))) %></li>
      <%- end -%>
  </ul>
</div>

<% end %>

app/views/catalog/_sub_items_sidebar.html.erb
<div id="sidebar-nav" class="well square-corners">
  <ul class="nav nav-list">
    <li>
      <fieldset id="assets">
        <legend>
          <h3>Items</h3>
        </legend>
        <div id="asset-list">
          <div class="clearfix">
               <p>See the items held within this <%= @document['type_ssi'] %></p>
               <p><%= sub_items_link(@document) %></p>
          </div>
        </div>
      </fieldset>
    </li>
  </ul>
</div>