config/routes.rb
ALLOW_DOTS ||= /[a-zA-Z0-9_.:-]+/

Rails.application.routes.draw do

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'
  
  # Switch over to this when home page has been created
  root to: 'pages#home'
  # root :to => "catalogue#index"

  resources :catalog, controller: 'catalog', path: '/catalogue', :constraints => { :id => ALLOW_DOTS, :format => false }

  # Add LB healthcheck page
  get 'healthcheck/rails-status' => 'pages#rails_status'

  %w[home about contact cookies help].each do |page|
    get page, controller: 'pages', action: page
  end
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalogue, only: [:index], as: 'catalog', path: '/catalogue', controller: 'catalog', :constraints => { :id => ALLOW_DOTS, :format => false } do
    concerns :searchable
    concerns :range_searchable
  end
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalogue', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/advanced_search/_advanced_search_submit_btns.html.erb
<div class="submit-buttons pull-right">
    <%= link_to t('blacklight_advanced_search.form.start_over'), advanced_search_path, :class =>"btn btn-default advanced-search-start-over" %>

    <%= submit_tag t('blacklight_advanced_search.form.search_btn'), :class=>'btn btn-primary advanced-search-submit', :id => "advanced-search-submit" %>
</div>

app/views/advanced_search/index.html.erb
<% @page_title = "Advanced search - #{application_name}" %>

<div class="col-sm-12">

    <h2>
        <%= t('blacklight_advanced_search.form.title') %>
        <%= link_to t('blacklight_advanced_search.form.start_over'), advanced_search_path, :class =>"btn btn-primary pull-right advanced-search-start-over" %>
    </h2>

    <div class="row">

        <div class="col-sm-8">
            <%= render 'advanced_search_form' %>
        </div>
        <div class="col-sm-4">
            <%= render "advanced_search_help" %>
        </div>

    </div>

</div>